name: Download Data

on:
  schedule:
    - cron: "0 0 1,11,21 * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependency
        run: pip install requests

      - name: Download data
        run: python src/download.py

      - name: Commit and push (data only)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config commit.gpgsign false
          git add data
          if git diff --cached --quiet; then
            echo "data: No changes to commit"
          else
            git commit -m ":monocle_face: add: data"
            git push
          fi
