name: Only Vis

on:
  workflow_dispatch:

env:
  WEBHOOK: ${{ secrets.WEBHOOK }}

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          pip install xlrd zerohertzLib'[api]'

      - name: Run Script
        run: |
          python src/data.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data
          git commit -m ":monocle_face: Add: Data" || echo "data: No changes to commit"
          git add prop/*/*.md
          git commit -m ":rocket: Docs: Rank" || echo "prop/*/*.md: No changes to commit"
          git add prop/*/*.png
          git commit -m ":art: Update: Visualization" || echo "prop/*/*.png: No changes to commit"
          git add prop/time
          git commit -m ":alarm_clock: Update: Time Series" || echo "time.tsv, prop/time: No changes to commit"
          git add -A
          git commit -m ":bento: Update: Etc." || echo "Etc.: No changes to commit"
          git push
